# Generated by Django 5.0.1 on 2024-01-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_item_category_post_comment_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_items',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='auctions.category'),
        ),
    ]
