# Generated by Django 5.0.1 on 2024-01-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_datetime_alter_comment_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='datetime',
            new_name='bid_datetime',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='datetime',
            new_name='comment_datetime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='post_datetime',
        ),
    ]
