# Generated by Django 5.0.1 on 2024-01-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_datetime_bid_bid_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_open',
            field=models.BooleanField(db_default=models.Value(True)),
        ),
    ]
