# Generated by Django 5.0.1 on 2024-01-10 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_post_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_open',
        ),
        migrations.AddField(
            model_name='post',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
